export function generateSpecMarkdown(data: {
  title: string;
  problem: string;
  targetUser: string;
  mvpObjective: string;
  scope: string;
  outOfScope?: string;
  features: string[];
  mainFlow: string;
  requiredData?: string;
  metrics?: string;
  risks?: string;
  assumptions?: string;
  suggestedStack?: string;
  nextIteration?: string;
}): string {
  const date = new Date().toISOString().split("T")[0];

  return `# MVP Spec: ${data.title}

*Generated: ${date}*

---

## 1. Problem

${data.problem}

## 2. Target User

${data.targetUser}

## 3. MVP Objective

${data.mvpObjective}

## 4. Scope

${data.scope}

${
  data.outOfScope
    ? `## 5. Out of Scope

${data.outOfScope}

`
    : ""
}## 6. Features

${data.features.map((f, i) => `${i + 1}. ${f}`).join("\n")}

## 7. Main Flow

${data.mainFlow}

${
  data.requiredData
    ? `## 8. Required Data

${data.requiredData}

`
    : ""
}${
  data.metrics
    ? `## 9. Success Metrics

${data.metrics}

`
    : ""
}${
  data.risks
    ? `## 10. Risks

${data.risks}

`
    : ""
}${
  data.assumptions
    ? `## 11. Assumptions

${data.assumptions}

`
    : ""
}${
  data.suggestedStack
    ? `## 12. Suggested Stack

${data.suggestedStack}

`
    : ""
}${
  data.nextIteration
    ? `## 13. Next Iteration

${data.nextIteration}

`
    : ""
}---

*Spec generated by Context Ops*
`;
}
