import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Header } from "@/components/layout/header";
import { Card, CardContent } from "@/components/ui/card";
import { CategoryBadge } from "@/components/ui/status-badge";
import { CopyMarkdownButton } from "@/components/specs/copy-markdown-button";
import { MarkdownRenderer } from "@/components/specs/markdown-renderer";

interface PageProps {
  params: { id: string };
}

export default async function SpecViewerPage({ params }: PageProps) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) return null;

  const spec = await prisma.mvpSpec.findFirst({
    where: {
      id: params.id,
      opportunity: { context: { userId: session.user.id } },
    },
    include: {
      opportunity: {
        select: {
          id: true,
          title: true,
          category: true,
          context: { select: { id: true, name: true } },
        },
      },
    },
  });

  if (!spec) notFound();

  return (
    <div className="flex flex-col">
      <Header
        title={spec.opportunity.title}
        description={`MVP Spec · ${spec.opportunity.context.name}`}
        actions={
          <div className="flex items-center gap-2">
            <CategoryBadge category={spec.opportunity.category} />
            <CopyMarkdownButton markdown={spec.markdownContent} />
          </div>
        }
      />

      <div className="p-6">
        <div className="mb-4">
          <Link
            href={`/opportunities/${spec.opportunity.id}`}
            className="inline-flex items-center gap-1 text-xs text-slate-400 hover:text-slate-200"
          >
            <ArrowLeft className="h-3 w-3" />
            Back to opportunity
          </Link>
        </div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-4">
          {/* Main spec */}
          <div className="lg:col-span-3">
            <Card>
              <CardContent className="p-6 lg:p-8">
                <MarkdownRenderer content={spec.markdownContent} />
              </CardContent>
            </Card>
          </div>

          {/* Sidebar meta */}
          <div className="space-y-4">
            <Card>
              <CardContent className="p-4 space-y-3">
                <div>
                  <p className="text-xs text-slate-500">Generated by</p>
                  <p className="text-sm text-slate-300 capitalize">{spec.generatedBy}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500">Created</p>
                  <p className="text-sm text-slate-300">
                    {new Date(spec.createdAt).toLocaleDateString()}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-slate-500">Context</p>
                  <Link
                    href={`/contexts/${spec.opportunity.context.id}`}
                    className="text-sm text-blue-400 hover:text-blue-300"
                  >
                    {spec.opportunity.context.name}
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
